version: '3.9'

services:
  redis_app:
    image: redis:alpine
    container_name: redis_app
    restart: always
    ports:
      - 6379:6379

  app:
    env_file:
      - .env
    build: .
    container_name: app
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
    links:
      - redis_app
