version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/var/lib/redis
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf

  app:
    env_file:
      - .env
    build: .
    container_name: app
    restart: always
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/usr/app
    links:
      - redis
    depends_on:
      - redis
